import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider,SignedOut,SignedIn,SignIn } from "@clerk/nextjs";
import { PdfProvider } from "./context/pdf-context.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Chat with PDF",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <PdfProvider>
    <ClerkProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen w-screen bg-zinc-900 flex justify-center items-center`}
      >
        <SignedOut>
          <SignIn />
        </SignedOut>
        <SignedIn>
          {children}
        </SignedIn>
      </body>
    </html>
    </ClerkProvider>
    </PdfProvider>
  );
}
